export const AUTH_START = 'AUTH__START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const ADD_WISH_LIST_SUCCESSFULL_MESSAGE = 'ADD_WISH_LIST_SUCCESSFULL_MESSAGE'
export const ADD_WISH_LIST_WARNING_MESSAGE = 'ADD_WISH_LIST_WARNING_MESSAGE'
export const SET_DEFAULT = 'SET_DEFAULT'